DEBUG                               : true
DOCKER_DEFAULT_DRIVER               : amazonec2
DOCKER_MIN_CONTAINERS               : 2
DOCKER_MAX_CONTAINERS               : 10
DOCKER_MAX_BOOTS_IN_LOOP            : 2
DOCKER_MAX_SHUTDOWNS_IN_LOOP        : 2
DOCKER_KILL_MODE                    : SOFT
DOCKER_SOFT_KILL_PATH               : /tmp
DOCKER_SOFT_KILL_FILENAME           : worker.die
AMAZONEC2_REGION                    : eu-west-1
AMAZONEC2_ACCESS_KEY                : null
AMAZONEC2_SECRET_KEY                : null
AMAZONEC2_VPC_ID                    : null
AMAZONEC2_ZONE                      : a
AMAZONEC2_SSH_USER                  : ubuntu
AMAZONEC2_INSTANCE_TYPE             : t2.micro
AMAZONEC2_AMI                       : null
AMAZONEC2_SUBNET_ID                 : null
AMAZONEC2_SECURITY_GROUP            : null
AMAZONEC2_PRIVATE_ADDRESS_ONLY      : true
EB_ALLOW_PRIVISION_CONTAINERS       : true
EB_TOLERANCE_THRESHOLD              : 3
STATSD_HOST                         : null
STATSD_PORT                         : 8125