DEBUG                                                     : true
OBSERVER_QUEUE_FEED_URL                                   : null
DOCKER_MACHINE_DEFAULT_DRIVER                             : amazonec2
DOCKER_MACHINE_MIN_CONTAINERS                             : 2
DOCKER_MACHINE_MAX_CONTAINERS                             : 10
DOCKER_MACHINE_MAX_BOOTS_IN_LOOP                          : 2
DOCKER_MACHINE_MAX_SHUTDOWNS_IN_LOOP                      : 2
DOCKER_MACHINE_KILL_MODE                                  : SOFT
DOCKER_MACHINE_SOFT_KILL_PATH                             : /tmp
DOCKER_MACHINE_SOFT_KILL_FILENAME                         : worker.die
DOCKER_MACHINE_CONTAINER_HOSTNAME_BASENAME                : ac-worker-
DOCKER_MACHINE_DRIVER_AMAZONEC2_REGION                    : eu-west-1
DOCKER_MACHINE_DRIVER_AMAZONEC2_ACCESS_KEY                : null
DOCKER_MACHINE_DRIVER_AMAZONEC2_SECRET_KEY                : null
DOCKER_MACHINE_DRIVER_AMAZONEC2_VPC_ID                    : null
DOCKER_MACHINE_DRIVER_AMAZONEC2_ZONE                      : a
DOCKER_MACHINE_DRIVER_AMAZONEC2_SSH_USER                  : ubuntu
DOCKER_MACHINE_DRIVER_AMAZONEC2_INSTANCE_TYPE             : t2.micro
DOCKER_MACHINE_DRIVER_AMAZONEC2_AMI                       : null
DOCKER_MACHINE_DRIVER_AMAZONEC2_SUBNET_ID                 : null
DOCKER_MACHINE_DRIVER_AMAZONEC2_SECURITY_GROUP            : null
DOCKER_MACHINE_DRIVER_AMAZONEC2_PRIVATE_ADDRESS_ONLY      : true
EB_ALLOW_PROVISION_WORKERS                                : true
EB_TOLERANCE_THRESHOLD                                    : 3
WORKER_DRIVER                                             : dockermachine
STATSD_HOST                                               : null
STATSD_PORT                                               : 8125
ENABLED_OBSERVERS                                         :
  - QueueObserver
  - TestObserver
