DOCKER_DEFAULT_DRIVER               : amazonec2
DOCKER_MIN_CONTAINERS               : 1
DOCKER_MAX_CONTAINERS               : 10
DOCKER_MAX_BOOTS_IN_LOOP            : null
DOCKER_MAX_SHUTDOWNS_IN_LOOP        : null
DOCKER_TERMINATE_MODE               : FALSE
AMAZONEC2_REGION                    : eu-west-1
AMAZONEC2_ACCESS_KEY                : AKIAIXSAJTUDBSFPZLNA
AMAZONEC2_SECRET_KEY                : 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
AMAZONEC2_VPC_ID                    : vpc-addacac5
AMAZONEC2_ZONE                      : a
AMAZONEC2_SSH_USER                  : centos
AMAZONEC2_INSTANCE_TYPE             : c3.large
AMAZONEC2_AMI                       : ami-f312b580
AMAZONEC2_SUBNET_ID                 : subnet-aedacac6
AMAZONEC2_SECURITY_GROUP            : default
AMAZONEC2_USE_PRIVATE_ADDRESS       : true
AMAZONEC2_PRIVATE_ADDRESS_ONYL      : true
EB_ALLOW_PRIVISION_CONTAINERS       : true
EB_MAX_PROVISION_CONTAINERS         : 5
STATSD_HOST                         : graphite.lab.minijuegos.com
STATSD_PORT                         : 8125
GEARMAN_HOST                        : 54.229.30.207
GEARMAN_PORT                        : 4730