DOCKER_DEFAULT_DRIVER               : amazonec2
DOCKER_MIN_CONTAINERS               : 1
DOCKER_MAX_CONTAINERS               : 10
DOCKER_MAX_BOOTS_IN_LOOP            : null
DOCKER_MAX_SHUTDOWNS_IN_LOOP        : null
DOCKER_TERMINATE_MODE               : FALSE
AMAZONEC2_REGION                    : eu-west-1
AMAZONEC2_ACCESS_KEY                : null
AMAZONEC2_SECRET_KEY                : null
AMAZONEC2_VPC_ID                    : null
AMAZONEC2_ZONE                      : null
AMAZONEC2_SSH_USER                  : null
AMAZONEC2_INSTANCE_TYPE             : null
AMAZONEC2_AMI                       : null
AMAZONEC2_SUBNET_ID                 : null
AMAZONEC2_SECURITY_GROUP            : null
AMAZONEC2_USE_PRIVATE_ADDRESS       : null
AMAZONEC2_PRIVATE_ADDRESS_ONYL      : null
EB_ALLOW_PRIVISION_CONTAINERS       : false
EB_MAX_PROVISION_CONTAINERS         : 0
STATSD_HOST                         : null
STATSD_PORT                         : 8125
GEARMAN_HOST                        : null
GEARMAN_PORT                        : 4730